apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  generation: 4
  labels:
    app: smx-pwa
    namespace: default
  name: dpl-smx-pwa
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smx-pwa
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: smx-pwa
    spec:
      imagePullSecrets:
      - name: secretpoldefcontainerregistrydev
      containers:
      - env:
        - name: NODE_ENV
          value: production
        - name: private-reg-container
        image: poldefcontainerregistrydev.azurecr.io/auto-pwa/_{Ambiente}_:$(Build.BuildId)
        name: smx-pwa
        ports:
        - containerPort: 80
          protocol: TCP
