apiVersion: v1
kind: Service
metadata:
  annotations:
  name: svc-pwa
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: smx-pwa
  sessionAffinity: None
  type: ClusterIP
